#!/bin/sh
set -u
IFS='
'

_echo() {
    printf '%s\n' "${1}"
}

_echo "minirc-ng"

_piddir="/run/minirc"
_config="/etc/minirc.json"

# load config
_get_all_daemons() {
    /usr/bin/jq -crM '.[] | .name' "${_config}"
}

_get_enabled_daemons() {
    /usr/bin/jq -crM '.[] | select(.enabled==true) | .name' "${_config}"
}

_get_field() {
    /usr/bin/jq -crM --arg name "${1}" ".[] | select(.name==\$name) | .${2}" "${_config}"
}

# ${1} -> service
# ${2} -> user
# ${3} -> command
# for logging use:
# > /tmp/logs/${1}.log instead of > /dev/null
_daemon_start() (

    _pidfile="${_piddir}/${1}.pid"
    _echo "Starting ${1}..."

    if _daemon_poll "${1}"
    then
        _echo "Error: ${_pidfile} exists"
    else

        _user="$(_get_field "${1}" "user")"
        _command="$(_get_field "${1}" "command")"
        if [ -z "${_user}" ] || [ -z "${_command}" ]
        then
            _echo "Error: unknown service: ${1}"
            exit 1
        fi

        /usr/bin/su -s "/bin/sh" - "${_user}" -c "${_command} > /dev/null 2>&1 & printf '%s' \${!}" > "${_pidfile}"

        _echo "User: ${_user}"
        _echo "Exec: ${_command}"
        _echo "PID: $(/usr/bin/cat "${_pidfile}")"
    fi
)

_daemon_stop() (

    _pidfile="${_piddir}/${1}.pid"
    _echo "Stopping ${1}..."

    if _daemon_poll "${1}"
    then
        _pid="$(/usr/bin/cat "${_pidfile}")"
        /usr/bin/kill --verbose --signal TERM --timeout 10000 KILL "${_pid}"
        _echo "Killed ${_pid}."
        /usr/bin/rm -rf "${_pidfile}"
    else
        _echo "Error: ${_pidfile} does not exist or service is not running"
    fi
)

_daemon_poll() (
    _pidfile="${_piddir}/${1}.pid"
    # if pidfile exists and pid from pidfile is running
    [ -f "${_pidfile}" ] && [ -h "/proc/$(/usr/bin/cat "${_pidfile}")/exe" ]
)

_on_init() (

    _echo "Mounting API filesystem..."
    /usr/bin/mountpoint -q /proc    || /usr/bin/mount -t proc proc /proc -o nosuid,noexec,nodev
    /usr/bin/mountpoint -q /sys     || /usr/bin/mount -t sysfs sys /sys -o nosuid,noexec,nodev
    /usr/bin/mountpoint -q /run     || /usr/bin/mount -t tmpfs run /run -o mode=0755,nosuid,nodev
    /usr/bin/mountpoint -q /tmp     || /usr/bin/mount -t tmpfs tmp /tmp -o mode=1777,nosuid,nodev
    /usr/bin/mountpoint -q /dev     || /usr/bin/mount -t devtmpfs dev /dev -o mode=0755,nosuid
    /usr/bin/mkdir -p /dev/pts /dev/shm
    /usr/bin/mountpoint -q /dev/pts || /usr/bin/mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
    /usr/bin/mountpoint -q /dev/shm || /usr/bin/mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

    _echo "Setting up loopback device..."
    /usr/sbin/ip link set up dev lo

    _echo "Initializing udev..."
    /usr/lib/systemd/systemd-udevd --daemon
    /usr/bin/udevadm trigger --action=add --type=subsystems
    /usr/bin/udevadm trigger --action=add --type=devices
    /usr/bin/udevadm settle

    _echo "Setting hostname..."
    /usr/bin/cat /etc/hostname >| /proc/sys/kernel/hostname

    _echo "Creating symlinks..."
    /usr/bin/ln -s /proc/kcore /dev/core 2>/dev/null
    /usr/bin/ln -s /proc/self/fd /dev/fd 2>/dev/null
    /usr/bin/ln -s /proc/self/fd/0 /dev/stdin 2>/dev/null
    /usr/bin/ln -s /proc/self/fd/1 /dev/stdout 2>/dev/null
    /usr/bin/ln -s /proc/self/fd/2 /dev/stderr 2>/dev/null

    _echo "Creating PID dir..."
    /usr/bin/install -m 755 -o root -g root -d "${_piddir}"

    _echo "Mounting fstab..."
    /usr/bin/mount -a
    /usr/bin/mount -o remount,rw /

    _echo "Creating utmp..."
    /usr/bin/install -m 664 -o root -g utmp /dev/null /var/run/utmp

    if [ -x "/etc/minirc.local" ]
    then
        _echo "Loading /etc/minirc.local..."
        /etc/minirc.local
    fi

    _echo "Starting daemons..."
    for _dmn in $(_get_enabled_daemons)
    do
        _daemon_start "${_dmn}"
    done
)

_on_shutdown() (

    _echo "Stopping daemons..."
    for _dmn in $(_get_all_daemons)
    do
        _daemon_poll "${_dmn}" && _daemon_stop "${_dmn}"
    done

    if [ -x "/etc/minirc.local.shutdown" ]
    then
        _echo "Loading /etc/minirc.local.shutdown..."
        /etc/minirc.local.shutdown
    fi

    _echo "Shutting down udev..."
    /usr/bin/killall -v -w systemd-udevd
)

_daemon_restart() {
    _daemon_stop "${1}"
    /usr/bin/sleep 1
    _daemon_start "${1}"
}

_usage() {
    _echo "Usage: rc [--help] <action> [daemon]"
    _echo ""
    _echo "Actions:"
    _echo "   rc l[ist]            shows status of all daemons"
    _echo "   rc start [daemon]    starts daemon"
    _echo "   rc stop [daemon]     stops daemon"
    _echo "   rc restart [daemon]  restarts daemon"
    exit 2
}

_not_root() {
    _echo "Root privileges are required to run this command"
    exit 1
}

[ "${#}" -eq 0 ] && _usage

case "${1}" in
init|shutdown)
    [ "${#}" -ne 1 ] && _usage
    [ "$(/usr/bin/id -u)" -ne 0 ] && _not_root
    _on_"${1}"
    ;;
start|stop|restart)
    [ "${#}" -ne 2 ] && _usage
    [ "$(/usr/bin/id -u)" -ne 0 ] && _not_root
    _daemon_"${1}" "${2}"
    ;;
list|l)
    [ "${#}" -ne 1 ] && _usage
    for _dmn in $(_get_all_daemons)
    do
        if _daemon_poll "${_dmn}"
        then
            printf '[\033[32mX\033[0m] %s\n' "${_dmn}"
        else
            _echo "[ ] ${_dmn}"
        fi
    done
    ;;
*)
    _usage
    ;;
esac
